# Generated by Django 6.0.2 on 2026-03-08 02:33

from django.db import migrations, models
from django.utils.text import slugify


def migrate_alunos_to_auth_user(apps, schema_editor):
    Aluno = apps.get_model('biblioteca', 'Aluno')
    User = apps.get_model('auth', 'User')

    for aluno in Aluno.objects.all().iterator():
        if User.objects.filter(id=aluno.id).exists():
            continue

        base_username = slugify((aluno.email or '').split('@')[0]) or f'aluno{aluno.id}'
        username = base_username[:150]
        suffix = 1

        while User.objects.filter(username=username).exists():
            tail = f'{suffix}'
            username = f'{base_username[:150 - len(tail)]}{tail}'
            suffix += 1

        User.objects.create(
            id=aluno.id,
            username=username,
            password=aluno.password,
            first_name=aluno.first_name,
            last_name=aluno.last_name,
            email=aluno.email,
            is_staff=aluno.is_staff,
            is_active=aluno.is_active,
            is_superuser=aluno.is_superuser,
            last_login=aluno.last_login,
            date_joined=aluno.date_joined,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_alunos_to_auth_user, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
