# Generated by Django 6.0.2 on 2026-03-08 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo_devolvido_delete_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('serie', models.CharField(choices=[('1EM', '1º ano'), ('2EM', '2º ano'), ('3EM', '3º ano')], max_length=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de aluno',
                'verbose_name_plural': 'Perfis de alunos',
            },
        ),
    ]
