# Generated by Django 6.0.2 on 2026-03-08 03:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alunoperfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoperfil',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificacaoAtrasoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(max_length=150)),
                ('data_referencia', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('erro', 'Erro')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='biblioteca.emprestimo')),
            ],
            options={
                'ordering': ['-enviado_em'],
                'unique_together': {('emprestimo', 'canal', 'data_referencia')},
            },
        ),
    ]
