# Generated by Django 6.0.2 on 2026-03-08 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alunoperfil_telefone_whatsapp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alunoperfil',
            index=models.Index(fields=['serie'], name='biblioteca__serie_721474_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['devolvido', 'data_devolucao'], name='biblioteca__devolvi_5df6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['data_retirada'], name='biblioteca__data_re_8d522d_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['aluno', 'devolvido'], name='biblioteca__aluno_i_1a73fc_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['nome_livro'], name='biblioteca__nome_li_b02fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaoatrasolog',
            index=models.Index(fields=['data_referencia', 'canal'], name='biblioteca__data_re_f5bdd8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaoatrasolog',
            index=models.Index(fields=['status'], name='biblioteca__status_ac8937_idx'),
        ),
    ]
