# Generated by Django 6.0.2 on 2026-03-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alunoperfil_biblioteca__serie_721474_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoperfil',
            name='telefone_whatsapp',
        ),
        migrations.AlterField(
            model_name='notificacaoatrasolog',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail')], max_length=20),
        ),
    ]
